### ISSUE TITLE
error due to pyqt4 

### ISSUE THREAD

**Issue by zhouyuking** [iris-edu/pyweed#109]
After installation as the instruction, an error comes out when pyweed is launched:

> ModuleNotFoundError: No module named 'PyQt4'

Conda automatically installed pyqt5. But after conda downgraded pyqt5 to pyqt4,  here comes another error:

> Qt internal error: qt_menu.nib could not be loaded. The .nib file should be placed in QtGui.framework/Versions/Current/Resources/  or in the resources directory of your application bundle.
> Abort trap: 6

**Comment by adam-iris** [comment]
Hi @zhouyuking, this should be fixed in the latest version (v1.0.1)
