### ISSUE TITLE
error during opening the app

### ISSUE THREAD

**Issue by pragyantpradab** [iris-edu/pyweed#123]
I installed PYWEED app in my macbook air m1. But when I am opening this app in terminal, it is showing error. The error message of terminal is attached as a screenshot.
![16278233208072720966862644485893](https://user-images.githubusercontent.com/47673444/127772009-76d5a86a-e52d-4a0b-a7ab-34fe9a086e8f.jpg)

Please have a look at these error and let me know how to solve this issue.

Ps - i previously installed it once in this same device and it was working then.

**Comment by adam-iris** [comment]
Most likely the saved configuration doesn't point to a valid FDSN datacenter. The easiest fix would be to delete ~/.pyweed/pyweed.ini, although this will wipe out any other configuration. You can also edit this file, the configured datacenters are given in the `[Data]` section:

    [Data]
    eventdatacenter = IRIS
    stationdatacenter = IRIS

**Comment by pragyantpradab** [comment]
> Most likely the saved configuration doesn't point to a valid FDSN datacenter. The easiest fix would be to delete ~/.pyweed/pyweed.ini, although this will wipe out any other configuration. You can also edit this file, the configured datacenters are given in the `[Data]` section:
> 
> ```
> [Data]
> eventdatacenter = IRIS
> stationdatacenter = IRIS
> ```

Thanks, It helped.
